CREATE DATABASE IF NOT EXISTS bd_crowdfunding;
USE bd_crowdfunding;


-- TABLAS MAESTRAS (Para los 3 Mantenimientos CRUD)
-- 1. Mantenimiento de Usuarios
CREATE TABLE USUARIO (
    Id_Usuario INT AUTO_INCREMENT,
    Nombre VARCHAR(50) NOT NULL,
    Apellido VARCHAR(50) NOT NULL,
    Correo VARCHAR(50) NOT NULL UNIQUE,
    Telefono VARCHAR(20), 
    Tipo_Usuario VARCHAR(50) NOT NULL, 
    CONSTRAINT PK_USUARIO PRIMARY KEY (Id_Usuario)
) ENGINE=InnoDB;
ALTER TABLE USUARIO ADD Clave VARCHAR(255) NOT NULL DEFAULT '12345';

-- 2. Mantenimiento de Categorías
CREATE TABLE CATEGORIA (
    Id_Categoria INT AUTO_INCREMENT,
    Nombre VARCHAR(50) NOT NULL UNIQUE,
    Descripcion VARCHAR(100),
    CONSTRAINT PK_CATEGORIA PRIMARY KEY (Id_Categoria)
) ENGINE=InnoDB;

-- 3. Mantenimiento de Métodos de Pago
CREATE TABLE METODO_DE_PAGO (
    Id_Metodo_Pago INT AUTO_INCREMENT,
    Token_Pago VARCHAR(100),
    Fecha_Expiracion DATE,
    Tipo_Pago VARCHAR(50) NOT NULL, 
    Estado_Pago VARCHAR(50) NOT NULL, 
    CONSTRAINT PK_METODO_PAGO PRIMARY KEY (Id_Metodo_Pago)
) ENGINE=InnoDB;


-- TABLAS DEL SISTEMA
-- 4. Registro de la Causa Social (RF 01)
CREATE TABLE CAUSA_SOCIAL (
    Id_Causa INT AUTO_INCREMENT,
    Titulo VARCHAR(50) NOT NULL,
    Descripcion VARCHAR(100) NOT NULL,
    Beneficiario VARCHAR(50) NOT NULL,
    Pais VARCHAR(50) NOT NULL,
    Ciudad VARCHAR(50) NOT NULL,
    USUARIO_Id_Usuario INT NOT NULL,  
    CONSTRAINT PK_CAUSA_SOCIAL PRIMARY KEY (Id_Causa),
    CONSTRAINT FK_CAUSA_USUARIO FOREIGN KEY (USUARIO_Id_Usuario) 
	REFERENCES USUARIO(Id_Usuario) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB;

-- 5. Tabla Intermedia: Relación Causa - Categoría (Muchos a Muchos)
CREATE TABLE CAUSA_CATEGORIA (
    CAUSA_SOCIAL_Id_Causa INT NOT NULL,
    CATEGORIA_Id_Categoria INT NOT NULL,
    CONSTRAINT PK_CAUSA_CATEGORIA PRIMARY KEY (CAUSA_SOCIAL_Id_Causa, CATEGORIA_Id_Categoria),
    CONSTRAINT FK_CC_CAUSA FOREIGN KEY (CAUSA_SOCIAL_Id_Causa) REFERENCES CAUSA_SOCIAL(Id_Causa) ON DELETE CASCADE,
    CONSTRAINT FK_CC_CATEGORIA FOREIGN KEY (CATEGORIA_Id_Categoria) REFERENCES CATEGORIA(Id_Categoria) ON DELETE RESTRICT
) ENGINE=InnoDB;

-- 6. Configuración de Meta y Plazo (RF 02)
CREATE TABLE META_PLAZO (
    Id_Meta INT AUTO_INCREMENT,
    Monto_Objetivo DECIMAL(12,2) NOT NULL,
    Monto_Minimo DECIMAL(12,2) NOT NULL,
    Fecha_Inicio DATE NOT NULL,
    Fecha_Finalizacion DATE NOT NULL,
    CAUSA_SOCIAL_Id_Causa INT NOT NULL,
    CONSTRAINT PK_META_PLAZO PRIMARY KEY (Id_Meta),
    CONSTRAINT FK_META_CAUSA FOREIGN KEY (CAUSA_SOCIAL_Id_Causa) REFERENCES CAUSA_SOCIAL(Id_Causa) ON DELETE CASCADE
) ENGINE=InnoDB;

-- 7. Carga de Evidencias de Progreso 
CREATE TABLE EVIDENCIA (
    Id_Evidencia INT AUTO_INCREMENT,
    Tipo_Evidencia VARCHAR(50) NOT NULL, 
    Archivo VARCHAR(255) NOT NULL,       
    Descripcion VARCHAR(100),
    CAUSA_SOCIAL_Id_Causa INT NOT NULL,
    CONSTRAINT PK_EVIDENCIA PRIMARY KEY (Id_Evidencia),
    CONSTRAINT FK_EVIDENCIA_CAUSA FOREIGN KEY (CAUSA_SOCIAL_Id_Causa) REFERENCES CAUSA_SOCIAL(Id_Causa) ON DELETE CASCADE
) ENGINE=InnoDB;

-- 8. Control Maestro de Suscripciones Recurrentes (RF 08)
CREATE TABLE SUSCRIPCION_DONANTE (
    Id_Suscripcion INT AUTO_INCREMENT,
    Fecha_prox DATE NOT NULL,
    Monto_Mensual DECIMAL(12,2) NOT NULL,
    Estado_Suscripcion VARCHAR(50) NOT NULL, 
    METODO_DE_PAGO_Id_Metodo_Pago INT NOT NULL,
    USUARIO_Id_Usuario INT NOT NULL,       
    CAUSA_SOCIAL_Id_Causa INT NOT NULL,    
    CONSTRAINT PK_SUSCRIPCION PRIMARY KEY (Id_Suscripcion),
    CONSTRAINT FK_SUSCRIPCION_METODO FOREIGN KEY (METODO_DE_PAGO_Id_Metodo_Pago) REFERENCES METODO_DE_PAGO(Id_Metodo_Pago),
    CONSTRAINT FK_SUSCRIPCION_USUARIO FOREIGN KEY (USUARIO_Id_Usuario) REFERENCES USUARIO(Id_Usuario),
    CONSTRAINT FK_SUSCRIPCION_CAUSA FOREIGN KEY (CAUSA_SOCIAL_Id_Causa) REFERENCES CAUSA_SOCIAL(Id_Causa) ON DELETE CASCADE
) ENGINE=InnoDB;

-- TABLAS TRANSACCIONALES Y DE AUDITORÍA
-- 9. Transacción de Donación 
CREATE TABLE DONACION (
    Id_Donacion INT AUTO_INCREMENT,
    Fecha_Donacion DATETIME DEFAULT CURRENT_TIMESTAMP,
    Tipo_Donacion VARCHAR(50) NOT NULL, 
    Es_Anonimo CHAR(1) DEFAULT 'N',     
    Total_Donado DECIMAL(12,2) NOT NULL,
    Comision DECIMAL(12,2) DEFAULT 0.00,
    METODO_DE_PAGO_Id_Metodo_Pago INT NOT NULL,
    USUARIO_Id_Usuario INT NOT NULL,
    CAUSA_SOCIAL_Id_Causa INT NOT NULL, 
    SUSCRIPCION_DONANTE_Id_Suscripcion INT NULL, 
    CONSTRAINT PK_DONACION PRIMARY KEY (Id_Donacion),
    CONSTRAINT FK_DONACION_METODO FOREIGN KEY (METODO_DE_PAGO_Id_Metodo_Pago) REFERENCES METODO_DE_PAGO(Id_Metodo_Pago),
    CONSTRAINT FK_DONACION_USUARIO FOREIGN KEY (USUARIO_Id_Usuario) REFERENCES USUARIO(Id_Usuario),
    CONSTRAINT FK_DONACION_CAUSA FOREIGN KEY (CAUSA_SOCIAL_Id_Causa) REFERENCES CAUSA_SOCIAL(Id_Causa),
    CONSTRAINT FK_DONACION_SUSC FOREIGN KEY (SUSCRIPCION_DONANTE_Id_Suscripcion) REFERENCES SUSCRIPCION_DONANTE(Id_Suscripcion)
) ENGINE=InnoDB;

-- 10. Emisión de Comprobantes (RF 09)
CREATE TABLE COMPROBANTE (
    Id_Comprobante INT AUTO_INCREMENT,
    Fecha_Emision DATETIME DEFAULT CURRENT_TIMESTAMP,
    pdf VARCHAR(255) NOT NULL, 
    Estado_Pago VARCHAR(50) NOT NULL, 
    QR_Verificacion VARCHAR(255),
    Code_Transaccion VARCHAR(100) NOT NULL UNIQUE,
    DONACION_Id_Donacion INT NOT NULL,
    CONSTRAINT PK_COMPROBANTE PRIMARY KEY (Id_Comprobante),
    CONSTRAINT FK_COMPROBANTE_DONACION FOREIGN KEY (DONACION_Id_Donacion) REFERENCES DONACION(Id_Donacion) ON DELETE RESTRICT
) ENGINE=InnoDB;

-- 11. Muro Social de Agradecimientos 
CREATE TABLE MURO_AGRADECIMIENTO (
    Id_Agradecimiento INT AUTO_INCREMENT,
    Mensaje VARCHAR(100) NOT NULL,
    Visibilidad CHAR(1) DEFAULT 'S', 
    Fecha_Publicacion DATETIME DEFAULT CURRENT_TIMESTAMP, 
    DONACION_Id_Donacion INT NOT NULL,
    CONSTRAINT PK_MURO PRIMARY KEY (Id_Agradecimiento),
    CONSTRAINT FK_MURO_DONACION FOREIGN KEY (DONACION_Id_Donacion) REFERENCES DONACION(Id_Donacion) ON DELETE CASCADE
) engine=InnoDB;

